- name: Run OS Infromation get PS script
  hosts: all 
  gather_facts: false
  vars:
    csvpath: C:\Windows\Temp\windows_info.csv
  tasks:
    - name: Run OS Information Get PS script
      script: /var/lib/awx/projects/_21__test_yaml/get-information.ps1  "{{ csvpath }}"
    - name: 生成したcsvファイルを取得
      fetch: src={{ csvpath }} dest=./outdir/ flat=yes
