- name: confirm OS information
  hosts: all

  tasks:
  - name: ベンダー名
    win_command: wmic csproduct get vendor
  - name: シリアルNo
    win_command: wmic bios get serialnumber
  - name: ホスト名
    win_command: hostname
  - name: IPアドレス
    win_command: ipconfig /all
  - name: 導入SW
    win_command: get-windowsfeature
